### PR TITLE
#13 index error list index out of range

### PR DESCRIPTION
**Pull request by santoshyadavdev**
The error is taken care of, there are few instances where data returned is 0, in which case we get this error.
But as limit set is so big , there may be issue where your there are any issues with the current network connection.
Also got Max retries exceeded with url: /api/v1/klines?symbol=XRPBTC&interval=1m&limit=500&startTime=152
2866601000&endTime=1522866600000 let me know if this is expected.

### CODE REVIEW

**Comment by samuelhei** [comment]
Nice work!

> Also got Max retries exceeded with url: /api/v1/klines?symbol=XRPBTC&interval=1m&limit=500&startTime=152
2866601000&endTime=1522866600000 let me know if this is expected.

I received the same message, it is not expected but I don't know if is new or not.

@anderson89marques can you review this too?

**Comment by anderson89marques** [comment]
Hi guys.
Thanks for your help @santoshyadav198613.
I detect some things. 

# Testing the issue and the pull request
To test the issue i executed the same command: 
 _$ kline-binance -i 1m -s XRPBTC -l 99999999999999 -st 01/01/2017 -e 05/04/2018_ 
and i had the same error at the same moment:
 
_$ 0%| | 219500/99999999999999_ 

So i tried to run with your pull request and no error was thrown.
But thinking about the problem and your change, i decide to run again, 
but putting the limit in 220000(+500 items from limit that throws the error) 
and i looked at the file(binance.csv) after.
The last 3 lines of the file below. (the first column is line number)

_219201  04/04/2018 23:58:00,0.00007229,0.00007238,0.00007214,0.00007237,45434.00000000
219202  04/04/2018 23:59:00,0.00007225,0.00007235,0.00007218,0.00007228,20444.00000000
219203  05/04/2018 00:00:00,0.00007228,0.00007233,0.00007223,0.00007233,24773.00000000_ 

The file should have 220001 lines(headers included), but have 219203 lines.
So 219203 is the max number of items in the period (-st 01/01/2017 -e 05/04/2018). 
Don't have more items to get in the API.

To confirm that I run again:
_$ kline-binance -i 1m -s XRPBTC -l 99999999999999 -st 01/01/2017 -e 05/04/2018_
and stopped in the below moment.

$ 0%|                                   | 225500/99999999999999 [05:26<37344086:52:10, 743.83it/s]

So i looked at the file again. Same result occurred. 
The last 3 lines of the file below. (the first column is line number)

_219201 04/04/2018 23:58:00,0.00007229,0.00007238,0.00007214,0.00007237,45434.00000000
219202 04/04/2018 23:59:00,0.00007225,0.00007235,0.00007218,0.00007228,20444.00000000
219203 05/04/2018 00:00:00,0.00007228,0.00007233,0.00007223,0.00007233,24773.00000000_

# My Conclusion:
Don't have more data to get for the period (-st 01/01/2017 -e 05/04/2018).  
Mabe stop the loop if klines was an empty list and 
inform the user that don't have more data to get for this period be the solution.
What do you think? some error in my points?
I hope i have expressed me clearly.

**Comment by santoshyadavdev** [comment]
@anderson89marques @samuelhei let me rerun this again, will handle this scenario.

**Comment by santoshyadavdev** [comment]
After making changes, getting below output.
venv) D:\Python\binance-downloader>"d:\python\basic\venv\scripts\python.exe" "D:\Python\Basic\venv\Scripts\\kline-binance" -i 1m -s XRPBT
C -l 99999999999999 -st 01/01/2017 -e 05/04/2018
  0%|                                                                          | 219000/99999999999999 [05:06<36001145:18:00, 771.58it/s]
download finished succesfully.

There is one problem though after 1500 records getting new line.

**Comment by anderson89marques** [comment]
Good job @santoshyadav198613,
What do you think about to put some message to inform the user why the download stopped before the limit?
So i merge your pull request and i close the issue?
What do you think?

**Comment by santoshyadavdev** [comment]
Hi @anderson89marques ,

Done added "All records downloaded for the provided date range." in case data is less than provided limit.

**Comment by samuelhei** [comment]
Thanks @santoshyadav198613 for the contribuition and the adjustments! Just merged the branch.

**Pull request merged**
